spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://3.36.28.63:3306/ATTENDANCE?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: gsmobile!@#
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure : error
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace
